export const PATHS = {
  HOME: '/',
  SHOP: '/shop',
  ABOUT: '/about',
  CONTACT: '/contact',
  FAQ: '/faq',
  PRODUCT_DETAIL: '/product/:id',
  LOGIN: '/login',
  REGISTER: '/register',
  ADMIN: '/admin',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PROFILE: '/profile',
  PRIVACY_POLICY: '/privacy-policy',
  PAYMENT_SUCCESS: '/payment-success',
  PAYMENT_FAILED: '/payment-failed',
  PAYMENT_QR: '/payment/:id',
};
